# Generated by Django 4.1.7 on 2023-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_quantity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='name',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
