# Generated by Django 4.1.7 on 2023-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_quantity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
