# Generated by Django 4.1.7 on 2023-03-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_quantity_number_for_summ'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
