# Generated by Django 4.1.7 on 2023-03-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message_sent_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='successfully',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
