# Generated by Django 4.1.7 on 2023-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_message_successfully'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ip',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
