# Generated by Django 4.1.7 on 2023-03-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_quantity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='open_ip',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
