# Generated by Django 4.1.7 on 2023-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_message_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='country',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='message',
            name='ip',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='message',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='open_ip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='successfully',
            field=models.IntegerField(default=0),
        ),
    ]
