# Generated by Django 4.1.7 on 2023-04-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='country',
            field=models.CharField(default='', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ip',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
