# Generated by Django 4.1.7 on 2023-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_message_country_alter_message_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='open_ip',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='successfully',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
