# Generated by Django 4.1.7 on 2023-04-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_message_open_ip_alter_message_sent_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analitic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('august', models.IntegerField()),
                ('may', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='anl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.analitic'),
            preserve_default=False,
        ),
    ]
