# Generated by Django 4.1.7 on 2023-04-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_analitic_message_anl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='anl',
        ),
        migrations.DeleteModel(
            name='Analitic',
        ),
    ]
