# Generated by Django 4.1.7 on 2023-04-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_analitic_message_anl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='anl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.analitic'),
        ),
    ]
