# Generated by Django 4.1.7 on 2023-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_message_anl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='anl',
        ),
        migrations.AddField(
            model_name='message',
            name='august',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='may',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Analitic',
        ),
    ]
