# Generated by Django 4.1.7 on 2023-04-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_message_august'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='country',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='message',
            name='may',
        ),
        migrations.RemoveField(
            model_name='message',
            name='number',
        ),
        migrations.RemoveField(
            model_name='message',
            name='open_ip',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_number',
        ),
        migrations.RemoveField(
            model_name='message',
            name='successfully',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
