# Generated by Django 4.1.7 on 2023-04-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_message_country_message_ip_message_may_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('send_email', models.IntegerField(default=0, null=True)),
                ('successfully_send_email', models.IntegerField(default=0, null=True)),
                ('open_email', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='analytics_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.analytics'),
        ),
    ]
