# Generated by Django 4.1.7 on 2023-04-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_rename_analytics_analytic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='send_email',
        ),
    ]
