# Generated by Django 4.1.7 on 2023-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_analytic_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='send_email',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
