# Generated by Django 4.1.7 on 2023-04-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_analytic_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='data',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
