# Generated by Django 4.1.7 on 2023-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_analytic_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='send_email',
        ),
        migrations.AlterField(
            model_name='analytic',
            name='open_email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='successfully_send_email',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
