# Generated by Django 4.1.7 on 2023-04-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_analytic_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='time',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
