# Generated by Django 4.1.7 on 2023-05-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_analytic_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='data',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='time',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='country',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
