# Generated by Django 4.1.7 on 2023-03-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_web', '0002_topic_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file_mail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
