# Generated by Django 4.1.7 on 2023-04-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_web', '0003_topic_file_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='file_mail',
        ),
    ]
